from setuptools import setup, find_packages

setup(
    name='TranscribeAI',
    version='0.1.0',
    description='Automatic Music Transcription using Machine Learning',
    author='Your Name',
    author_email='ruqayyamustafa82@gmail.com',
    url='https://github.com/ruqayya82/Automated-Music-Transcription-Model,
    packages=find_packages(where='src'),
    package_dir={'': 'src'},
    python_requires='>=3.8',
    install_requires=[
        'librosa>=0.10.1',
        'numpy>=1.24.3',
        'scipy>=1.11.4',
        'tensorflow>=2.15.0',
        'torch>=2.1.2',
        'pretty_midi>=0.2.10',
        'music21>=9.1.0',
        'flask>=3.0.0',
        'scikit-learn>=1.3.2',
        'matplotlib>=3.8.2',
        'pandas>=2.1.4',
        'pyyaml>=6.0.1',
        'tqdm>=4.66.1',
    ],
    extras_require={
        'dev': [
            'pytest>=7.4.3',
            'black>=23.12.1',
            'flake8>=7.0.0',
            'jupyter>=1.0.0',
        ],
    },
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Topic :: Multimedia :: Sound/Audio :: Analysis',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
    ],
    keywords='music transcription machine-learning audio-processing midi musicxml',
)
