# TranscribeAI Configuration File

# Audio Processing Parameters
audio:
  sample_rate: 22050  # Hz
  frame_length: 2048  # samples
  hop_length: 512     # samples
  n_fft: 2048        # FFT size
  n_mels: 128        # Number of mel bands
  fmin: 50           # Minimum frequency (Hz)
  fmax: 8000         # Maximum frequency (Hz)

# Pitch Detection Parameters
pitch_detection:
  method: 'pyin'  # Options: 'pyin', 'yin', 'autocorrelation'
  fmin: 65.0      # Minimum pitch (C2, Hz)
  fmax: 2093.0    # Maximum pitch (C7, Hz)
  frame_length: 2048
  hop_length: 512
  threshold: 0.1  # Confidence threshold for pitch detection

# Onset Detection Parameters
onset_detection:
  method: 'spectral_flux'  # Options: 'spectral_flux', 'energy', 'hfc'
  hop_length: 512
  threshold: 0.5
  pre_max: 3
  post_max: 3
  pre_avg: 3
  post_avg: 3
  delta: 0.07
  wait: 30

# Note Quantization
quantization:
  min_note_duration: 0.1  # seconds
  tempo: 120              # BPM
  time_signature: '4/4'

# MIDI Parameters
midi:
  instrument: 0  # 0 = Acoustic Grand Piano
  velocity: 80   # Note velocity (0-127)

# Model Parameters
model:
  input_shape: [128, 128]  # [n_mels, time_steps]
  learning_rate: 0.001
  batch_size: 32
  epochs: 100
  early_stopping_patience: 10

# File Paths
paths:
  data_dir: 'data'
  sample_audio_dir: 'data/sample_audio'
  datasets_dir: 'data/datasets'
  models_dir: 'saved_models'
  output_dir: 'output'

# Web Interface
web:
  title: 'TranscribeAI - Automatic Music Transcription'
  max_upload_size: 10  # MB
  supported_formats: ['wav', 'mp3', 'ogg', 'flac']
